class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'appName': 'سلة+',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'about': 'حول التطبيق',
      'support': 'الدعم الفني',
      'contactUs': 'اتصل بنا',
      'projectInfo': 'معلومات المشروع',
      'version': 'الإصدار',
      'map': 'الخريطة',
      'bins': 'السلات',
      'notifications': 'الإشعارات',
      'addBin': 'إضافة سلة',
      'editBin': 'تعديل السلة',
      'binName': 'اسم السلة',
      'binType': 'نوع السلة',
      'address': 'العنوان',
      'fillLevel': 'نسبة الامتلاء',
      'location': 'الموقع',
      'search': 'بحث...',
      'delete': 'حذف',
      'edit': 'تعديل',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'confirmDelete': 'تأكيد الحذف',
      'deleteMessage': 'هل أنت متأكد من حذف هذه السلة؟',
      'allNotifications': 'جميع الإشعارات',
      'importantNotifications': 'الإشعارات المهمة',
      'noBins': 'لا توجد سلات',
      'noResults': 'لا توجد نتائج للبحث',
      'startNow': 'ابدأ الآن',
      'welcome': 'مرحباً بك في تطبيق إدارة سلات المهملات الذكية',
      'emptyBinList': 'قائمة السلات فارغة',
      'addNewBin': 'إضافة سلة جديدة',
      'selectLocation': 'اختر موقع السلة',
      'binDetails': 'تفاصيل السلة',
      'fillLevelStatus': 'حالة الامتلاء',
      'regularBin': 'سلة عادية',
      'recyclingBin': 'سلة إعادة تدوير',
      'hazardousBin': 'سلة نفايات خطرة',
    },
    'fr': {
      'appName': 'Poubelle+',
      'settings': 'Paramètres',
      'language': 'Langue',
      'about': 'À propos',
      'support': 'Support',
      'contactUs': 'Contactez-nous',
      'projectInfo': 'Info du projet',
      'version': 'Version',
      'map': 'Carte',
      'bins': 'Poubelles',
      'notifications': 'Notifications',
      'addBin': 'Ajouter une poubelle',
      'editBin': 'Modifier la poubelle',
      'binName': 'Nom de la poubelle',
      'binType': 'Type de poubelle',
      'address': 'Adresse',
      'fillLevel': 'Niveau de remplissage',
      'location': 'Emplacement',
      'search': 'Rechercher...',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'confirmDelete': 'Confirmer la suppression',
      'deleteMessage': 'Êtes-vous sûr de vouloir supprimer cette poubelle?',
      'allNotifications': 'Toutes les notifications',
      'importantNotifications': 'Notifications importantes',
      'noBins': 'Aucune poubelle',
      'noResults': 'Aucun résultat trouvé',
      'startNow': 'Commencer',
      'welcome':
          'Bienvenue dans l\'application de gestion intelligente des déchets',
      'emptyBinList': 'Liste des poubelles vide',
      'addNewBin': 'Ajouter une nouvelle poubelle',
      'selectLocation': 'Sélectionnez l\'emplacement',
      'binDetails': 'Détails de la poubelle',
      'fillLevelStatus': 'Niveau de remplissage',
      'regularBin': 'Poubelle régulière',
      'recyclingBin': 'Poubelle de recyclage',
      'hazardousBin': 'Poubelle de déchets dangereux',
    },
  };

  final String languageCode;

  AppLocalizations(this.languageCode);

  String get currentLanguage => languageCode == 'ar' ? 'العربية' : 'Français';

  String translate(String key) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
